name: billy
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Add firebase
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.1
  cloud_firestore: any
  flutter_stream_listener: ^1.0.0
  flutter_linear_datepicker: ^2.0.0
  #Firebase Storage
  firebase_storage :
  #Add fonts
  google_fonts: ^1.1.1
  #Add pdf syncfusion plugin
  syncfusion_flutter_pdf: ^18.4.32-beta
  #extract data from mail
  imap_client: ^0.2.9

  #open url from app
  url_launcher: ^6.0.3
  #open website inside app
  webview_flutter: ^2.0.4
  #pick up an image
  image_picker: ^0.5.4+3
  #ocr
  tesseract_ocr: ^0.3.1
  #shared preferences
  shared_preferences: any

  dropdown_search: ^0.6.1

  flutter_picker: ^2.0.1
  googleapis: any
  googleapis_auth: any

  enough_mail: any

  #Path provider
  path_provider: ^1.3.0

  #floating action button
  flutter_speed_dial: ^1.2.1

  #Chart & Graphs
  charts_flutter: ^0.10.0
  fl_chart: ^0.35.0

  #Firebase ml vision
  firebase_ml_vision: any

  #Camera package
  camera: ^0.5.8+11

  #intl package
  intl: ^0.16.1

  #Web scraper
  web_scraper: ^0.0.9


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - images/
    - pdf/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
